import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './vars.css';
import './globals.css';
import { ReactQueryClientProvider } from '@/providers/ReactQueryProvider';
import { AuthProvider } from '@/providers/AuthProvider';
import { Header } from '@/components/Header/Header';
import styles from './layout.module.scss';
import cn from 'classnames';
import { Providers } from '@/providers/Providers';
import { Button } from '@chakra-ui/react';
import Link from 'next/link';
import { AntdRegistry } from '@ant-design/nextjs-registry';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="ru">
      <meta name="viewport" content="width=device-width, initial-scale=1"></meta>

      <body className={cn(inter.className, styles.body)}>
        <Providers>
          <AntdRegistry>
            <Header />
            {children}
            <Link href="/event/create">
              <Button colorScheme="orange" size={'lg'} className={styles.btn}>
                Создать событие!
              </Button>
            </Link>
          </AntdRegistry>
        </Providers>
      </body>
    </html>
  );
}
